spring.datasource.url=jdbc:postgresql://localhost:5433/lead_scraper
spring.datasource.username=postgres
spring.datasource.password=Piyya

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
gemini.model=${GEMINI_MODEL:gemini-3.6-flash}
contact.provider.api.key=${CONTACT_PROVIDER_API_KEY:}
logging.level.org.springframework.security=TRACE
spring.config.import=optional:file:.env[.properties]
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG